### ISSUE TITLE
OCR結果に入る大量の半角スペースの除去

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#12]
ON/OFFできるべきかもだけど、これは読みやすさのために必要だと思う。

**Comment by guredora403** [comment]
まず半角スペースを除去できるのだろうか。通常版で。

**Comment by yamahubuki** [comment]
まともにできれば素晴らしい。むりなら置換で全部飛ばしてしまえ

**Comment by guredora403** [comment]
そんなことをして大丈夫なのか？英語が入っていたとか。

**Comment by guredora403** [comment]
それをやろうと思ったらtesseractかgoogleか判定を行う必要がある。
