### ISSUE TITLE
ディレクトリ追加への対応

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#27]
D&Dおよび貼り付けコマンドではディレクトリの追加を試みることができる。

そして、ディレクトリ名をa.pdfのようにしておけば、リスト追加・変換開始まで進めてしまう。

ディレクトリを探索して対応ファイルを探すようにするか、もしくはディレクトリをはじくようにするか(当然手間だが前者が望ましい)が必要。

**Comment by guredora403** [comment]
どこかにディレクトリから画像ファイルだけを持ってくる才気処理を入れておく。ただ.jpgと.JPGの用に大文字と小文字どちらも受け入れなければならないので対処が必要。
とりあえずファイル一覧だけとってきてaddFileにかけるのが良さそう。

**Comment by guredora403** [comment]
授業中にいろいろ考えると間違ってフォルダーを貼り付けると大量のファイルが展開されるのはうざいと思うんですがどうでしょうか。

**Comment by yamahubuki** [comment]
それは…間違える人が悪いんじゃないかなあ。
zipとかで大量のファイルをもらう機会はあるので、あったら便利だと思います。

**Comment by guredora403** [comment]
ただまあファイルリストとってくるのが結構大変なんで将来的に対応するかもしれません
