### ISSUE TITLE
包括的なエラー処理

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#29]
以下のような、いちいち対処してられないエラーがありますが、そのまま落ちると問題なので、ocr.pyのファイル操作や通信が関わるところでは、まとめてtryして、exceptできたエラーを全部まとめて「変換に失敗しました。詳細：(エラーをそのままプリント)
とするような対応が必要そうです。

[一例]
File "Ocr.py", line 45, in google_ocr
    media_body = MediaFileUpload(local_file_path, mimetype="application/vnd.google-apps.document", resumable=True)
(この先外部モジュールのため省略)
PermissionError: [Errno 13] Permission denied: 'a.pdf'

**Comment by guredora403** [comment]
それをやってしまうとocr.pyの中で個別にexceptしているエラー処理に影響してしまうのではないでしょうか。

**Comment by yamahubuki** [comment]
try-exceptは入子にできます。
既存の処理で回収しきれなかったものだけ、新たに書くtry-exceptで拾えばよいかと思います。
もしくは、既存のtryで範囲が十分なのであれば、exceptを1つ増やして対応するのでもよいかと思います。

**Comment by guredora403** [comment]
とりあえずダイアログに表示するのは問題だと思うのでerrorlog.txtに保存してそっち見てくれって感じでよいでしょうか。
