### ISSUE TITLE
認証用ブラウザーの規定ブラウザー対応

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/SOC#31]
現在IEにしか対応していないので規定ブラウザーを取得してそれで開くようにする。規定ブラウザーの取得方法は不明。

**Comment by guredora403** [comment]
規定browserの取得方法がまじめにわからない。
いろいろ調べるとレジストリにあるらしいがそこにはIEのパスが登録されていた。実際の規定はchrome。
別のキーから規定browserのprogIdは取得できた。これを絶対パスに変換できれば理想。
webbrowserというモジュールのソースコードを読みあさればおそらくわかると思うが自分にはハードルが高い。

**Comment by guredora403** [comment]
urlをwin+rで実行すると規定ブラウザーが開く。
pythonからwin+rで実行すると同じ事ができてそこからpidを取ってくることができれば可能かと思われる。
ちなみにviews/main.pyのwx.process.Openの実行ファイルパスをurlにしてみたりしたけどだめだった。

**Comment by yamahubuki** [comment]
Googleのセキュリティ対策への対応として現在はwebbrowser.openを使っているので本件は解決済み。クローズします。
このころは認証完了後にブラウザを自動で閉じるためwebbrowser.openを使いたくなかったんですが、ソフトにフックされたブラウザからは認証が通せなくなったので、ユーザーに閉じてもらうように変更済みです。
