### ISSUE TITLE
アイスランド語で起動するとdllの読み込みに失敗する

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/SOC#33]
具体的なエラーメッセージは以下の通り。
Fatal error detected: Error loading Python DLL 'C:\soc\python37.dll'.
LoadLibrary: The system cannot find the file specified.
なぜか中国語とかだと普通に起動しますがさすがに国際対応をうたうなら対処した方がいいかと思われます。

**Comment by yamahubuki** [comment]
さすがにもう何が起こっているかはわかりません。
\あたりが噛んでるかもですが、調べようもありません。

**Comment by guredora403** [comment]
おそらくその環境ではほかのpythonアプリケーションも起動できなさそうですしどうしようもないのでしょうか。
