### ISSUE TITLE
PDFに文字情報が含まれるか否かの判定誤り

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#45]
別途通知の通り、PowerPointから変換したファイルをテキスト情報なしと誤判定する場合がある。

**Comment by yamahubuki** [comment]
一旦PDF⇒テキスト変換してみないとダメかも…。

**Comment by guredora403** [comment]
pdfinfoの出力結果のfilesizeが0 bytesかどうかで判定していたのですがなんらかの原因で0 bytesにならなかったみたいです。別の方法を考えなければなりません。

**Comment by guredora403** [comment]
pdfinfoを直接呼び出すと0 bytesではありませんでした。どうやら出力結果を解析しているときになにか怒ってるみたいです。

**Comment by guredora403** [comment]
いえこっちの操作ミスで出てました。普通に0 bytesになってますね。テキスト変換すれば普通にとれるのでそれがよさげです。
