### ISSUE TITLE
アップデートチェックを非同期処理にする

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#50]
このままではサーバ障碍児やプロキシ環境下ではソフトが数十秒以上フリーズします。
スレッドに分けるなど、対策が必要です。

**Comment by guredora403** [comment]
非同期処理にしてしまうとユーザーがチェック注意ocrを開始することができてしまったりして問題があるのでタイムアウトを指定しておくぐらいが良いと思われます。

settings.iniでユーザーが秒数を指定できればいいのではないでしょうか。

**Comment by yamahubuki** [comment]
それくらいが無難かもねえ
