### ISSUE TITLE
ファイル変換の中止ができない

### ISSUE THREAD

**Issue by hrk-fujii** [actlaboratory/SOC#59]
変換中ダイアログのキャンセルボタンが動作しない。

**Comment by yamahubuki** [comment]
バージョンアップによりキャンセルボタンはなくなっているが、どちらにしてもキャンセル昨日は必要。
ステータス一覧上でDelキー、およびコンテキストメニューからの中止処理を実装する。

**Comment by yamahubuki** [comment]
Delは将来の削除のために残しておき、ひとまずコンテキストメニューだけ実装。
いったん認識だけキャンセルできるようにしたので、変換も止められるようになったらクローズとします。
