### ISSUE TITLE
pyinstallerの都合でビルドしても動かない

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#6]
下記サイトの手順でpyinstallerをいじると解決するそうです。
https://qiita.com/akitooo/items/eb82a5f335d8ca9c9faf

appbeyorでうまくいくように、build.pyの修正、どうにもならなければspecファイルの追加をお願いします。

**Comment by yncat** [comment]
close されてるけど、これだれかがやってくれたの？

**Comment by guredora403** [comment]
修正版をコミットしたので大丈夫かと思いまして閉じました

**Comment by yamahubuki** [comment]
issueに関連したコミットの場合は、コミットメッセージに「#issue番号」を入れてください。

また、特定キーワードを使うと、コミットのpushと同時にissueをクローズすることもできます。

issueのやり取りをみて経過が分かるよう、整理していくとよいです。

**Comment by guredora403** [comment]
#6を修正というコミットメッセージのコミットを出していましたがfixes #6でクローズされるみたいなのでこれからはそっちを使います。

**Comment by yamahubuki** [comment]
#の前と数字の後にはそれぞれ半角スペースが必要なので注意してください。

また、漏れた場合は後からコミットのページに行ってコメント欄に入力しておくとよいです。
ただし、ここではfixed等を指定してのクローズは使えません。
