### ISSUE TITLE
googleで大容量のPDFがOcrできない問題

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/SOC#63]
googleのOcrに40MBぐらいのPDFを投げるとＧｏｏｇｌｅからError 500が返ってきます。おそらくある程度容量が大きいファイルだとOcrできないようです。原因はわかりません。

**Comment by yamahubuki** [comment]
本日、PDFは必ず1ページごとに分けてからOCRするようにしました。
現状、ページ分けしてもこの問題を引き起こすPDFファイルというのもすぐには見つからないためいったんクローズします。
