### ISSUE TITLE
全角文字を含むディレクトリでは起動しないようにする

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#7]
起動時にディレクトリ名をチェックして、全角文字が入ってたら警告表示して終了にしましょう。

チェックは正規表現またはfor文で文字コード128以降の文字をひっかけるのが簡単です。

**Comment by yncat** [comment]
全角文字を含むディレクトリでOCRエンジンが動かないとか？

**Comment by yamahubuki** [comment]
SOC本体を置いたディレクトリの名前に全角文字が含まれていると、tesseractがうまく動かないようです。

linux由来のソフトなので、文字化けでもしているんでしょう。

**Comment by guredora403** [comment]
とりあえず全角ファイル名が見つかったらダイアログを表示して終了するでいいと思いますがsoc.pyに書き込んでも大丈夫でしょうか。

**Comment by yamahubuki** [comment]
いいけど、app.pyでやることを推奨します。
そうしないとlogへの記録もできないし。

SOC.pyはただの起動スクリプトだと思ってください。

**Comment by guredora403** [comment]
では音声読み上げの準備の直前に入れておきます。
