### ISSUE TITLE
キャンセル処理を実装する

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/SOC#86]
一応キャンセルイベントとかあったほうがいいと思う。
どちらかというと中止かもしれないが。
sourceでいうとスキャナが利用不可だった時はそのtaskの処理はすべてキャンセルとなる。ただ、この場合はsourceが勝手に終了すればtaskも勝手に終了するはず（未検証）だが、通知は必要？
また、ファイルごとにキャンセル/中止処理が必要。認識状況のファイル一覧の上のコンテキストメニューとかからできるようにするといいと思う。
jobにフラグを設定することで実装が可能と思われる。
ファイルごとのキャンセル/中止処理の場合、認識処理を完全に止める場合と変換処理だけ止めて変換済みのページだけとりあえず認識するという2段階があると思うので要検討。

**Comment by yamahubuki** [comment]
#59 と重複のためクローズします。
