### ISSUE TITLE
表示言語を切り替えできるようにする

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/SOC#9]
初回起動時に選択ウィンドウを出すのがよさげ。
言語一覧の取得は翻訳モジュールでできたはず。

**Comment by guredora403** [comment]
ユーザーのシステム言語を取得して自動的に設定されるようにするのはどうでしょう。

**Comment by yamahubuki** [comment]
いいけど、その場合は英語でも日本語でもない可能性を必ず加味してください。
そして、それをテストするのがものすごく面倒であることをお忘れなきように。

**Comment by guredora403** [comment]
それはlocale emulatorというソフトを使えば実行ファイルならばそこまで面倒な作業にはなりません。おそらくサポートしてない言語だったときは選択ウインドウを出した方がいいと思うので選択ウインドウを実装して後からシステム言語を取得って感じの方がいいかもですね

**Comment by yncat** [comment]
日本語環境だが英語を使いたいというケースはあり得る

**Comment by guredora403** [comment]
とりあえず言語選択ダイアログはつきましたがシステムの言語を自動判定した言語選択ダイアログを作った方がいいでしょうか。翻訳は使えないですが条件分岐すれば可能かと。
